/**
 * Stylebook UI API surface — re-exports split clients (stylebook-api + Agate projects).
 */

export { fetchProjects, type Project } from "@/lib/stylebook-api/projects"
export {
  LOCATION_TYPES,
  type CanonicalListSort,
  type CanonicalLocation,
  type LinkedMention,
  type LinkedSubstrateItem,
  type LinkedSubstratesResponse,
  type Location,
  type LocationMentionsResponse,
  type PaginatedCanonicalLocationResponse,
  type PaginatedLocationResponse,
  createCanonicalLocation,
  createLocation,
  deleteCanonicalLocation,
  deleteLocation,
  getCanonicalLocation,
  getCanonicalLocationLegacy,
  getCanonicalLocationMentions,
  getLocation,
  getLocationMentions,
  linkSubstrateToCanonical,
  listCanonicalLinkedSubstrates,
  listCanonicalLocations,
  listCanonicalLocationsLegacy,
  listCanonicalLocationTypes,
  listLocationOptions,
  listLocations,
  patchCanonicalLocation,
  unlinkSubstrateFromCanonical,
  updateCanonicalLocationGeometry,
  updateLocation,
  updateLocationGeometry,
} from "@/lib/stylebook-api/locations"
export {
  type AcceptCandidateBody,
  type AcceptCandidateResponse,
  type CanonicalSuggestion,
  type Candidate,
  type CandidateCluster,
  type CandidateContextItem,
  type CandidateContextResponse,
  type ListCandidatesFilterOptions,
  type ListClustersOptions,
  type PaginatedCandidatesResponse,
  type PaginatedClustersResponse,
  type SuggestedCanonicalItem,
  type SuggestedCanonicalsResponse,
  acceptCandidate,
  deferCandidate,
  getCandidateContext,
  getSuggestedCanonicals,
  listCandidates,
  listClusters,
  listLocationCandidateTypes,
  updateCandidateNote,
} from "@/lib/stylebook-api/candidates"
export {
  type AgentType,
  type EntityTypeStats,
  type Stats,
  getAgentTypes,
  getStats,
} from "@/lib/stylebook-api/stats-stub"

export {
  type AnalyzeGeoJsonResponse,
  analyzeImportGeoJson,
  type ImportGeoJsonMetaPropertyMapping,
  type ImportGeoJsonResponse,
  importGeoJson,
} from "@/lib/stylebook-api/imports"
export {
  type AcceptPersonCandidateBody,
  type AcceptPersonCandidateResponse,
  type ListPersonCandidatesFilterOptions,
  type PaginatedPersonCandidatesResponse,
  type PersonCandidate,
  type PersonCandidateContextItem,
  type PersonCandidateContextResponse,
  type PersonCanonicalSuggestion,
  type SuggestedPersonCanonicalItem,
  type SuggestedPersonCanonicalsResponse,
  acceptPersonCandidate,
  deferPersonCandidate,
  getPersonCandidateContext,
  getSuggestedPersonCanonicals,
  listPersonCandidateTypes,
  listPersonCandidates,
  updatePersonCandidateNote,
} from "@/lib/stylebook-api/personCandidates"
export {
  type CanonicalPerson,
  type CanonicalPersonListFilters,
  type CanonicalPersonListSort,
  type LinkedPersonMention,
  type LinkedPersonSubstrateItem,
  type LinkedPersonSubstratesResponse,
  type PersonMentionsResponse,
  type PaginatedCanonicalPersonResponse,
  type Person,
  createCanonicalPerson,
  deleteCanonicalPerson,
  getCanonicalPerson,
  getCanonicalPersonLegacy,
  getCanonicalPersonMentions,
  getPerson,
  linkPersonSubstrateToCanonical,
  listCanonicalLinkedPersonSubstrates,
  listCanonicalPeople,
  listCanonicalPeopleLegacy,
  listCanonicalPersonTypes,
  patchCanonicalPerson,
  unlinkPersonSubstrateFromCanonical,
} from "@/lib/stylebook-api/people"
export { listPeople } from "@/lib/stylebook-api/entityListStubs"
