/**
 * Stylebook UI API surface — re-exports split clients (stylebook-api + Agate projects).
 */

export { fetchProjects, type Project } from "@/lib/stylebook-api/projects"
export {
  LOCATION_TYPES,
  type CanonicalListSort,
  type CanonicalLocation,
  type LinkedMention,
  type LinkedSubstrateItem,
  type LinkedSubstratesResponse,
  type Location,
  type LocationMentionsResponse,
  type PaginatedLocationResponse,
  createCanonicalLocation,
  deleteCanonicalLocation,
  deleteLocation,
  getCanonicalLocation,
  getCanonicalLocationMentions,
  getLocation,
  getLocationMentions,
  linkSubstrateToCanonical,
  listCanonicalLinkedSubstrates,
  listCanonicalLocations,
  listCanonicalLocationTypes,
  listLocationOptions,
  listLocations,
  patchCanonicalLocation,
  unlinkSubstrateFromCanonical,
  updateCanonicalLocationGeometry,
  updateLocation,
  updateLocationGeometry,
} from "@/lib/stylebook-api/locations"
export {
  type AcceptCandidateBody,
  type AcceptCandidateResponse,
  type CanonicalSuggestion,
  type Candidate,
  type CandidateCluster,
  type CandidateContextItem,
  type CandidateContextResponse,
  type ListCandidatesFilterOptions,
  type ListClustersOptions,
  type PaginatedCandidatesResponse,
  type PaginatedClustersResponse,
  type SuggestedCanonicalItem,
  type SuggestedCanonicalsResponse,
  acceptCandidate,
  clearLocationCandidateRecommendation,
  deferCandidate,
  getCandidateContext,
  getSuggestedCanonicals,
  listCandidates,
  listClusters,
  listLocationCandidateTypes,
  updateCandidateNote,
} from "@/lib/stylebook-api/candidates"
export {
  type AgentType,
  type EntityTypeStats,
  type Stats,
  getAgentTypes,
  getStats,
} from "@/lib/stylebook-api/stats-stub"
export {
  type CleanupCheck,
  type CleanupCheckKind,
  type CleanupChecksResponse,
  type DuplicateLocationCluster,
  type GetCleanupCheckResultsParams,
  type ListCleanupChecksParams,
  type PaginatedDuplicateClustersResponse,
  type CleanupLocationIssue,
  type CleanupMismatchIssue,
  type CleanupQuestionableOrganizationIssue,
  type PaginatedCleanupListResults,
  type PaginatedCleanupLocationIssuesResponse,
  type PaginatedCleanupMismatchIssuesResponse,
  type PaginatedCleanupQuestionableOrganizationsResponse,
  type CleanupCheckRun,
  type CleanupCheckRunStatus,
  getCleanupCheckResults,
  getDuplicateLocationClusters,
  getDuplicatePersonClusters,
  getDuplicateOrganizationClusters,
  getMissingGeometryLocations,
  getLatestCleanupCheckRun,
  listCleanupChecks,
  pollCleanupCheckRun,
  runCleanupCheck,
  runCleanupCheckCount,
  refreshPersistedCleanupCheckCount,
  startCleanupCheckRun,
  mergeCleanupLocationCanonical,
  mergeCleanupPersonCanonical,
  mergeCleanupOrganizationCanonical,
  deleteEmptyCleanupLocationCanonical,
  deleteEmptyCleanupPersonCanonical,
  deleteEmptyCleanupOrganizationCanonical,
  dismissCleanupIssue,
  type CleanupDismissalResponse,
  type MergeCleanupCanonicalResponse,
  type MergeCleanupLocationCanonicalResponse,
  type CleanupClusterCanonical,
  type DuplicateCluster,
  type CleanupAiModel,
  type CleanupAiModelsResponse,
  type CleanupAiReview,
  type CleanupAiProposal,
  type CleanupAiProposalAction,
  type CleanupAiProposalsResponse,
  type CleanupAiProposalActionResponse,
  listCleanupAiModels,
  startCleanupAiReview,
  getCleanupAiReview,
  getLatestCleanupAiReview,
  cancelCleanupAiReview,
  listCleanupAiProposals,
  acceptCleanupAiProposal,
  rejectCleanupAiProposal,
} from "@/lib/stylebook-api/cleanup"
export {
  type CandidateAiModel,
  type CandidateAiReview,
  type CandidateAiReviewEntityType,
  listCandidateAiModels,
  startCandidateAiReview,
  getCandidateAiReview,
  getLatestCandidateAiReview,
  cancelCandidateAiReview,
} from "@/lib/stylebook-api/candidateAiReview"

export {
  type AnalyzeCsvResponse,
  type AnalyzeGeoJsonResponse,
  analyzeImportCsvOrganizations,
  analyzeImportCsvPeople,
  analyzeImportGeoJson,
  type ImportCsvResponse,
  type ImportGeoJsonMetaPropertyMapping,
  type ImportGeoJsonResponse,
  importCsvOrganizations,
  importCsvPeople,
  importGeoJson,
  type OrganizationCsvFieldMappings,
  type PersonCsvFieldMappings,
} from "@/lib/stylebook-api/imports"
export {
  type AcceptPersonCandidateBody,
  type AcceptPersonCandidateResponse,
  type ListPersonCandidatesFilterOptions,
  type PaginatedPersonCandidatesResponse,
  type PersonCandidate,
  type PersonCandidateContextItem,
  type PersonCandidateContextResponse,
  type PersonCanonicalSuggestion,
  type SuggestedPersonCanonicalItem,
  type SuggestedPersonCanonicalsResponse,
  acceptPersonCandidate,
  clearPersonCandidateRecommendation,
  deferPersonCandidate,
  getPersonCandidateContext,
  getSuggestedPersonCanonicals,
  listPersonCandidateTypes,
  listPersonCandidates,
  updatePersonCandidateNote,
} from "@/lib/stylebook-api/personCandidates"
export {
  type CanonicalPerson,
  type CanonicalPersonListFilters,
  type CanonicalPersonListSort,
  type LinkedPersonMention,
  type LinkedPersonSubstrateItem,
  type LinkedPersonSubstratesResponse,
  type PersonMentionsResponse,
  type PaginatedCanonicalPersonResponse,
  type Person,
  createCanonicalPerson,
  deleteCanonicalPerson,
  getCanonicalPerson,
  getCanonicalPersonMentions,
  getPerson,
  linkPersonSubstrateToCanonical,
  listCanonicalLinkedPersonSubstrates,
  listCanonicalPeople,
  listCanonicalPersonTypes,
  patchCanonicalPerson,
  unlinkPersonSubstrateFromCanonical,
} from "@/lib/stylebook-api/people"
export {
  type AcceptOrganizationCandidateBody,
  type AcceptOrganizationCandidateResponse,
  type ListOrganizationCandidatesFilterOptions,
  type OrganizationCandidate,
  type OrganizationCandidateContextItem,
  type OrganizationCandidateContextResponse,
  type OrganizationCanonicalSuggestion,
  type PaginatedOrganizationCandidatesResponse,
  type SuggestedOrganizationCanonicalItem,
  type SuggestedOrganizationCanonicalsResponse,
  acceptOrganizationCandidate,
  clearOrganizationCandidateRecommendation,
  deferOrganizationCandidate,
  getOrganizationCandidateContext,
  getSuggestedOrganizationCanonicals,
  listOrganizationCandidateTypes,
  listOrganizationCandidates,
  updateOrganizationCandidateNote,
} from "@/lib/stylebook-api/organizationCandidates"
export {
  type CanonicalOrganization,
  type CanonicalOrganizationListFilters,
  type CanonicalOrganizationListSort,
  type LinkedOrganizationMention,
  type LinkedOrganizationSubstrateItem,
  type LinkedOrganizationSubstratesResponse,
  type Organization,
  type OrganizationMentionsResponse,
  type PaginatedCanonicalOrganizationResponse,
  createCanonicalOrganization,
  deleteCanonicalOrganization,
  getCanonicalOrganization,
  getCanonicalOrganizationMentions,
  getOrganization,
  linkOrganizationSubstrateToCanonical,
  listCanonicalLinkedOrganizationSubstrates,
  listCanonicalOrganizations,
  listCanonicalOrganizationTypes,
  patchCanonicalOrganization,
  unlinkOrganizationSubstrateFromCanonical,
} from "@/lib/stylebook-api/organizations"
export { listPeople, listOrganizations } from "@/lib/stylebook-api/entityListStubs"
