"""Repo-root .env helpers for local init."""

from __future__ import annotations

import re
import secrets
import shutil
from dataclasses import dataclass
from pathlib import Path

from cryptography.fernet import Fernet

_ENV_LINE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)=(.*)$")
_SECRET_KEYS = ("MASTER_ENCRYPTION_KEY", "SESSION_SECRET")


@dataclass(frozen=True)
class EnvEnsureReport:
    env_path: Path
    created_env_file: bool
    generated_keys: tuple[str, ...]


def find_repo_root(start: Path | None = None) -> Path:
    current = (start or Path.cwd()).resolve()
    for candidate in (current, *current.parents):
        if (candidate / "infra" / "docker-compose.yml").is_file() and (
            candidate / "Makefile"
        ).is_file():
            return candidate
    raise FileNotFoundError(
        "Could not find Backfield repo root (expected Makefile and infra/docker-compose.yml)"
    )


def read_env_values(path: Path) -> dict[str, str]:
    if not path.is_file():
        return {}
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        match = _ENV_LINE.match(stripped)
        if match is None:
            continue
        key, raw_value = match.group(1), match.group(2)
        values[key] = _unquote(raw_value.strip())
    return values


def _unquote(value: str) -> str:
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        return value[1:-1]
    return value


def generate_master_encryption_key() -> str:
    return Fernet.generate_key().decode()


def generate_session_secret() -> str:
    return secrets.token_urlsafe(32)


def ensure_repo_env_file(repo_root: Path) -> EnvEnsureReport:
    env_path = repo_root / ".env"
    example_path = repo_root / ".env.example"
    created_env_file = False
    if not env_path.is_file():
        created_env_file = True
        if example_path.is_file():
            shutil.copy(example_path, env_path)
        else:
            env_path.write_text(
                "# Local Backfield environment (generated by backfield init)\n",
                encoding="utf-8",
            )

    values = read_env_values(env_path)
    generated: list[str] = []
    updates: dict[str, str] = {}
    if not values.get("MASTER_ENCRYPTION_KEY", "").strip():
        updates["MASTER_ENCRYPTION_KEY"] = generate_master_encryption_key()
        generated.append("MASTER_ENCRYPTION_KEY")
    if not values.get("SESSION_SECRET", "").strip():
        updates["SESSION_SECRET"] = generate_session_secret()
        generated.append("SESSION_SECRET")
    if updates:
        write_env_values(env_path, updates)
    return EnvEnsureReport(
        env_path=env_path,
        created_env_file=created_env_file,
        generated_keys=tuple(generated),
    )


def write_env_values(path: Path, updates: dict[str, str]) -> None:
    lines = path.read_text(encoding="utf-8").splitlines() if path.is_file() else []
    remaining = dict(updates)
    output: list[str] = []
    seen: set[str] = set()
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            output.append(line)
            continue
        match = _ENV_LINE.match(stripped)
        if match is None:
            output.append(line)
            continue
        key = match.group(1)
        if key in remaining:
            output.append(f"{key}={remaining.pop(key)}")
            seen.add(key)
        else:
            output.append(line)
            seen.add(key)
    for key in _SECRET_KEYS:
        if key in remaining:
            output.append(f"{key}={remaining.pop(key)}")
            seen.add(key)
    for key, value in remaining.items():
        output.append(f"{key}={value}")
    path.write_text("\n".join(output).rstrip() + "\n", encoding="utf-8")


def load_env_into_process(env_path: Path) -> None:
    import os

    for key, value in read_env_values(env_path).items():
        os.environ.setdefault(key, value)
