"""Person canonical persist, policy, and link helpers."""

from backfield_entities.entities.person.catalog_provenance import (
    PERSON_CATALOG_EDITORIAL_PROVENANCES,
    is_person_catalog_editorial_provenance,
)
from backfield_entities.entities.person.persist import (
    allocate_unique_person_canonical_slug,
    apply_canonical_persist_plan,
    apply_canonical_persist_plan_review_only,
    assert_canonical_link_invariant,
    create_standalone_canonical,
    link_substrate_to_canonical_atomic,
    link_to_existing_canonical,
    materialize_new_canonical_and_link,
    maybe_prune_ingest_orphan_person_canonical,
    person_canonical_has_editorial_catalog_provenance,
    rank_canonical_suggestions_for_substrate,
    refresh_aliases_for_linked_person,
    requeue_substrate_after_story_remove,
    seed_aliases_for_canonical_label,
    sync_substrate_person_into_stylebook,
    unlink_substrate_from_canonical,
    upsert_alias_for_canonical_text,
)
from backfield_entities.entities.person.policy import (
    decide_person_canonical_persist_plan,
    find_existing_person_canonical_id_by_alias,
    find_existing_person_canonical_id_by_identity,
    person_may_materialize_canonical_after_recall,
    plan_has_ambiguous_person_canonical_match,
    plan_requires_llm_person_canonical_adjudication,
    rank_person_canonical_recall_matches,
)
from backfield_entities.entities.person.recall import retrieve_person_canonical_candidates
from backfield_entities.entities.person.types import (
    PERSON_NATURE_VALUES,
    PERSON_TYPE_VALUES,
    derive_person_sort_key,
    normalize_person_text,
    normalize_person_type,
    person_identity_fingerprint,
)

__all__ = [
    "PERSON_CATALOG_EDITORIAL_PROVENANCES",
    "PERSON_NATURE_VALUES",
    "PERSON_TYPE_VALUES",
    "allocate_unique_person_canonical_slug",
    "apply_canonical_persist_plan",
    "apply_canonical_persist_plan_review_only",
    "assert_canonical_link_invariant",
    "create_standalone_canonical",
    "decide_person_canonical_persist_plan",
    "derive_person_sort_key",
    "find_existing_person_canonical_id_by_alias",
    "find_existing_person_canonical_id_by_identity",
    "is_person_catalog_editorial_provenance",
    "link_substrate_to_canonical_atomic",
    "link_to_existing_canonical",
    "materialize_new_canonical_and_link",
    "maybe_prune_ingest_orphan_person_canonical",
    "normalize_person_text",
    "normalize_person_type",
    "person_canonical_has_editorial_catalog_provenance",
    "person_identity_fingerprint",
    "person_may_materialize_canonical_after_recall",
    "plan_has_ambiguous_person_canonical_match",
    "plan_requires_llm_person_canonical_adjudication",
    "rank_canonical_suggestions_for_substrate",
    "rank_person_canonical_recall_matches",
    "refresh_aliases_for_linked_person",
    "requeue_substrate_after_story_remove",
    "retrieve_person_canonical_candidates",
    "seed_aliases_for_canonical_label",
    "sync_substrate_person_into_stylebook",
    "unlink_substrate_from_canonical",
    "upsert_alias_for_canonical_text",
]
