"""Internal caps for automatic connection inference (v1 constants)."""

from __future__ import annotations

MAX_LINKED_ENTITIES_PER_TYPE = 16
MIN_PAIR_EVIDENCE_SCORE_FOR_ENTITY_RESERVATION = 30
MAX_EDGES_RETURNED_PER_FAMILY = 12
MAX_CREATED_EDGES_PER_ITEM = 20
MAX_SNIPPETS_PER_ENTITY = 3
MAX_SNIPPET_CHARS = 220
MAX_CANDIDATE_PAIRS_PER_ARTICLE = 64
MAX_CANDIDATE_PAIRS_PER_BATCH = 8
MAX_INLINE_CONNECTION_REQUESTS = 4
MAX_TOTAL_CONNECTION_REQUESTS = 8
MAX_CONNECTION_REQUEST_CONCURRENCY = 2
