"""Internal caps for automatic connection inference (v1 constants)."""

from __future__ import annotations

MAX_LINKED_ENTITIES_PER_TYPE = 32
MIN_PAIR_EVIDENCE_SCORE_FOR_ENTITY_RESERVATION = 30
MAX_CREATED_EDGES_PER_ITEM = 40
MAX_SNIPPETS_PER_ENTITY = 3
MAX_SNIPPET_CHARS = 220
MAX_CANDIDATE_PAIRS_PER_ARTICLE = 128
MAX_CANDIDATE_PAIRS_PER_BATCH = 8
# Inline Backfield Output uses the full per-article request budget; deferred overflow is off.
MAX_INLINE_CONNECTION_REQUESTS = 16
MAX_TOTAL_CONNECTION_REQUESTS = 16
MAX_CONNECTION_REQUEST_CONCURRENCY = 2
